# Generated by Django 3.0.6 on 2020-07-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200706_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='shin.jpg', null=True, upload_to=''),
        ),
    ]
