# Generated by Django 3.0.8 on 2020-10-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200706_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='css/images/shin.jpg', null=True, upload_to=''),
        ),
    ]
